# Generated by Django 5.2.14 on 2026-08-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=200)),
                ('tags', models.CharField(help_text="Comma-separated, e.g. 'Django, React, Postgres'", max_length=200)),
                ('category', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=60)),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(help_text='e.g. Active, Shipped, In progress', max_length=30)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', '-year'],
            },
        ),
    ]
