# Generated by Django 5.2.14 on 2026-08-25 12:05

from django.db import migrations

PLACEHOLDER_PROJECTS = [
    {
        "title": "Project One",
        "slug": "project-one",
        "short_description": "One-line placeholder description of this project goes here.",
        "tags": "Tag, Tag, Tag",
        "category": "Category",
        "role": "Role",
        "year": 2026,
        "status": "Active",
        "order": 1,
        "featured": True,
    },
    {
        "title": "Project Two",
        "slug": "project-two",
        "short_description": "One-line placeholder description of this project goes here.",
        "tags": "Tag, Tag, Tag",
        "category": "Category",
        "role": "Role",
        "year": 2025,
        "status": "Shipped",
        "order": 2,
        "featured": False,
    },
    {
        "title": "Project Three",
        "slug": "project-three",
        "short_description": "One-line placeholder description of this project goes here.",
        "tags": "Tag, Tag, Tag",
        "category": "Category",
        "role": "Role",
        "year": 2025,
        "status": "In progress",
        "order": 3,
        "featured": False,
    },
]


def seed_projects(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for data in PLACEHOLDER_PROJECTS:
        Project.objects.create(**data)


def unseed_projects(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Project.objects.filter(slug__in=[p["slug"] for p in PLACEHOLDER_PROJECTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_projects, unseed_projects),
    ]
