# Generated by Django 5.2.14 on 2026-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('greeting', models.CharField(default="HELLO, I'M SHAHBAZ.", max_length=100)),
                ('line_one', models.CharField(default='I BUILD.', max_length=60)),
                ('line_two', models.CharField(default='I WRITE.', max_length=60)),
                ('name_first', models.CharField(default='SHAHBAZ', max_length=40)),
                ('name_last', models.CharField(default='KHAN', max_length=40)),
                ('line_three', models.CharField(default='I EXPLORE.', max_length=60)),
                ('roles', models.CharField(default='DEVELOPER / FREELANCER / WRITER', max_length=150)),
                ('meta_line_one', models.CharField(blank=True, max_length=150)),
                ('meta_line_two', models.CharField(blank=True, max_length=150)),
                ('meta_line_three', models.CharField(blank=True, max_length=150)),
                ('year', models.CharField(default='2026', max_length=20)),
                ('location', models.CharField(default='SILVASSA, DADRA & NAGAR HAVELI', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
