# Generated by Django 5.2.14 on 2026-08-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_hero_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='statement',
            field=models.CharField(default='Good ideas deserve more than thought—they deserve to be built.', max_length=300),
        ),
    ]
