# Generated by Django 5.2.14 on 2026-08-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_herocontent_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='role',
            field=models.CharField(choices=[('primary', 'Primary (identity)'), ('quote', 'Quote')], default='primary', max_length=20),
        ),
    ]
