# Generated by Django 5.2.14 on 2026-08-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_about_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsnapshot',
            name='currently_building',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutsnapshot',
            name='currently_exploring',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutsnapshot',
            name='currently_label',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='aboutsnapshot',
            name='currently_learning',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutsnapshot',
            name='currently_writing',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutsnapshot',
            name='eyebrow',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutsnapshot',
            name='headline_one',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='aboutsnapshot',
            name='headline_sub',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutsnapshot',
            name='headline_three',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='aboutsnapshot',
            name='headline_two',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='aboutsnapshot',
            name='paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='greeting',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='line_one',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='line_three',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='line_two',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='name_first',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='name_last',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='roles',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='statement',
            field=models.CharField(max_length=300),
        ),
    ]
