# Generated by Django 5.2.14 on 2026-08-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_seed_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(max_length=100)),
                ('title_line_one', models.CharField(max_length=60)),
                ('title_line_two', models.CharField(max_length=60)),
                ('lede', models.CharField(max_length=300)),
                ('background_heading', models.CharField(max_length=100)),
                ('background_paragraph', models.TextField()),
                ('care_heading', models.CharField(max_length=100)),
                ('care_paragraph', models.TextField()),
                ('philosophy_eyebrow', models.CharField(max_length=100)),
                ('philosophy_quote', models.TextField()),
                ('skills_eyebrow', models.CharField(max_length=100)),
                ('languages_label', models.CharField(max_length=100)),
                ('languages', models.CharField(help_text="Comma-separated, e.g. 'Python, Java'", max_length=300)),
                ('frameworks_label', models.CharField(max_length=100)),
                ('frameworks', models.CharField(help_text="Comma-separated, e.g. 'Django, React'", max_length=300)),
                ('learning_label', models.CharField(max_length=100)),
                ('learning', models.CharField(help_text="Comma-separated, e.g. 'AI Agents'", max_length=300)),
                ('going_eyebrow', models.CharField(max_length=100)),
                ('going_paragraph', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
