# Generated by Django 5.2.14 on 2026-08-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_about_skills_finalize'),
        ('projects', '0011_seed_real_first_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=150)),
                ('period', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('organization', models.CharField(max_length=150)),
                ('period', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_sub', models.CharField(max_length=300)),
                ('languages_label', models.CharField(max_length=100)),
                ('frameworks_label', models.CharField(max_length=100)),
                ('learning_label', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frameworks', models.ManyToManyField(related_name='resume_frameworks', to='projects.tag')),
                ('languages', models.ManyToManyField(related_name='resume_languages', to='projects.tag')),
                ('learning', models.ManyToManyField(related_name='resume_learning', to='projects.tag')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
