# Generated by Django 5.2.14 on 2026-09-03 12:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_sync_about_skills_with_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(storage=core.models.resume_storage, upload_to='resume/'),
        ),
    ]
